### ISSUE TITLE
Too thin walls in Paletten_Eurobox_1m3.stl

### ISSUE THREAD

**Issue by jaybee79** [Worldworms/MobaLedLib_3D_Prints#1]
Hi,
I tried to print Paletten_Eurobox_1m3.stl but it seems the slicer (Creality Slicer 1.2.3 based on Cura software) doesn't recognise the walls of the box as walls, so my result has missing walls and looks like a table with a Europalette upside down on it's top. Any idea what I can do or is is possible to change the thickness of the walls, so that my printer (Ender 3D) will be able to print it as designed?

**Comment by Worldworms** [comment]
Hello,

 

the Euroboxes are designed for a 0,3mm nozzle, it can be that if you slice them with a 0,4mm nozzle, the walls will be missing 

Try it with a 0,3mm nozzle.

 

Best regards

 

Von: jaybee79 <notifications@github.com> 
Gesendet: Mittwoch, 2. Dezember 2020 20:26
An: Worldworms/MobaLedLib_3D_Prints <MobaLedLib_3D_Prints@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Worldworms/MobaLedLib_3D_Prints] Too thin walls in Paletten_Eurobox_1m3.stl (#1)

 

Hi,
I tried to print Paletten_Eurobox_1m3.stl but it seems the slicer (Creality Slicer 1.2.3 based on Cura software) doesn't recognise the walls of the box as walls, so my result has missing walls and looks like a table with a Europalette upside down on it's top. Any idea what I can do or is is possible to change the thickness of the walls, so that my printer (Ender 3D) will be able to print it as designed?

**Comment by jaybee79** [comment]
Hi, 

this seems to be the issue. My printer has a 0.4mm nozzle, so it looks like I'll have to redesign it by myself.
Thanks for your help!
